require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by the Rails when you ran the scaffold generator.

describe ClubsController do

  def mock_club(stubs={})
    @mock_club ||= mock_model(Club, stubs).as_null_object
  end

  describe "GET index" do
    it "assigns all clubs as @clubs" do
      Club.stub(:all) { [mock_club] }
      get :index
      assigns(:clubs).should eq([mock_club])
    end
  end

  describe "GET show" do
    it "assigns the requested club as @club" do
      Club.stub(:find).with("37") { mock_club }
      get :show, :id => "37"
      assigns(:club).should be(mock_club)
    end
  end

  describe "GET new" do
    it "assigns a new club as @club" do
      Club.stub(:new) { mock_club }
      get :new
      assigns(:club).should be(mock_club)
    end
  end

  describe "GET edit" do
    it "assigns the requested club as @club" do
      Club.stub(:find).with("37") { mock_club }
      get :edit, :id => "37"
      assigns(:club).should be(mock_club)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "assigns a newly created club as @club" do
        Club.stub(:new).with({'these' => 'params'}) { mock_club(:save => true) }
        post :create, :club => {'these' => 'params'}
        assigns(:club).should be(mock_club)
      end

      it "redirects to the created club" do
        Club.stub(:new) { mock_club(:save => true) }
        post :create, :club => {}
        response.should redirect_to(club_url(mock_club))
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved club as @club" do
        Club.stub(:new).with({'these' => 'params'}) { mock_club(:save => false) }
        post :create, :club => {'these' => 'params'}
        assigns(:club).should be(mock_club)
      end

      it "re-renders the 'new' template" do
        Club.stub(:new) { mock_club(:save => false) }
        post :create, :club => {}
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested club" do
        Club.stub(:find).with("37") { mock_club }
        mock_club.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, :id => "37", :club => {'these' => 'params'}
      end

      it "assigns the requested club as @club" do
        Club.stub(:find) { mock_club(:update_attributes => true) }
        put :update, :id => "1"
        assigns(:club).should be(mock_club)
      end

      it "redirects to the club" do
        Club.stub(:find) { mock_club(:update_attributes => true) }
        put :update, :id => "1"
        response.should redirect_to(club_url(mock_club))
      end
    end

    describe "with invalid params" do
      it "assigns the club as @club" do
        Club.stub(:find) { mock_club(:update_attributes => false) }
        put :update, :id => "1"
        assigns(:club).should be(mock_club)
      end

      it "re-renders the 'edit' template" do
        Club.stub(:find) { mock_club(:update_attributes => false) }
        put :update, :id => "1"
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested club" do
      Club.stub(:find).with("37") { mock_club }
      mock_club.should_receive(:destroy)
      delete :destroy, :id => "37"
    end

    it "redirects to the clubs list" do
      Club.stub(:find) { mock_club }
      delete :destroy, :id => "1"
      response.should redirect_to(clubs_url)
    end
  end

end
