require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by the Rails when you ran the scaffold generator.

describe TennisReservationsController do

  def mock_tennis_reservation(stubs={})
    @mock_tennis_reservation ||= mock_model(TennisReservation, stubs).as_null_object
  end

  describe "GET index" do
    it "assigns all tennis_reservations as @tennis_reservations" do
      TennisReservation.stub(:all) { [mock_tennis_reservation] }
      get :index
      assigns(:tennis_reservations).should eq([mock_tennis_reservation])
    end
  end

  describe "GET show" do
    it "assigns the requested tennis_reservation as @tennis_reservation" do
      TennisReservation.stub(:find).with("37") { mock_tennis_reservation }
      get :show, :id => "37"
      assigns(:tennis_reservation).should be(mock_tennis_reservation)
    end
  end

  describe "GET new" do
    it "assigns a new tennis_reservation as @tennis_reservation" do
      TennisReservation.stub(:new) { mock_tennis_reservation }
      get :new
      assigns(:tennis_reservation).should be(mock_tennis_reservation)
    end
  end

  describe "GET edit" do
    it "assigns the requested tennis_reservation as @tennis_reservation" do
      TennisReservation.stub(:find).with("37") { mock_tennis_reservation }
      get :edit, :id => "37"
      assigns(:tennis_reservation).should be(mock_tennis_reservation)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "assigns a newly created tennis_reservation as @tennis_reservation" do
        TennisReservation.stub(:new).with({'these' => 'params'}) { mock_tennis_reservation(:save => true) }
        post :create, :tennis_reservation => {'these' => 'params'}
        assigns(:tennis_reservation).should be(mock_tennis_reservation)
      end

      it "redirects to the created tennis_reservation" do
        TennisReservation.stub(:new) { mock_tennis_reservation(:save => true) }
        post :create, :tennis_reservation => {}
        response.should redirect_to(tennis_reservation_url(mock_tennis_reservation))
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved tennis_reservation as @tennis_reservation" do
        TennisReservation.stub(:new).with({'these' => 'params'}) { mock_tennis_reservation(:save => false) }
        post :create, :tennis_reservation => {'these' => 'params'}
        assigns(:tennis_reservation).should be(mock_tennis_reservation)
      end

      it "re-renders the 'new' template" do
        TennisReservation.stub(:new) { mock_tennis_reservation(:save => false) }
        post :create, :tennis_reservation => {}
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested tennis_reservation" do
        TennisReservation.stub(:find).with("37") { mock_tennis_reservation }
        mock_tennis_reservation.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, :id => "37", :tennis_reservation => {'these' => 'params'}
      end

      it "assigns the requested tennis_reservation as @tennis_reservation" do
        TennisReservation.stub(:find) { mock_tennis_reservation(:update_attributes => true) }
        put :update, :id => "1"
        assigns(:tennis_reservation).should be(mock_tennis_reservation)
      end

      it "redirects to the tennis_reservation" do
        TennisReservation.stub(:find) { mock_tennis_reservation(:update_attributes => true) }
        put :update, :id => "1"
        response.should redirect_to(tennis_reservation_url(mock_tennis_reservation))
      end
    end

    describe "with invalid params" do
      it "assigns the tennis_reservation as @tennis_reservation" do
        TennisReservation.stub(:find) { mock_tennis_reservation(:update_attributes => false) }
        put :update, :id => "1"
        assigns(:tennis_reservation).should be(mock_tennis_reservation)
      end

      it "re-renders the 'edit' template" do
        TennisReservation.stub(:find) { mock_tennis_reservation(:update_attributes => false) }
        put :update, :id => "1"
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested tennis_reservation" do
      TennisReservation.stub(:find).with("37") { mock_tennis_reservation }
      mock_tennis_reservation.should_receive(:destroy)
      delete :destroy, :id => "37"
    end

    it "redirects to the tennis_reservations list" do
      TennisReservation.stub(:find) { mock_tennis_reservation }
      delete :destroy, :id => "1"
      response.should redirect_to(tennis_reservations_url)
    end
  end

end
